# The overall template of the release notes
template: |
  $CHANGES

# Setting the formatting and sorting for the release notes body
name-template: Version (set version here)
change-template: "* $TITLE ([#$NUMBER]($URL))"
sort-by: merged_at
sort-direction: ascending
replacers:
  - search: "##"
    replace: "###"

# Organizing the tagged PRs into unified categories
categories:
  - title: "Breaking changes"
    labels:
      - "breaking change"
  - title: "Features"
    labels:
      - "feature"
  - title: "Enhancements"
    labels:
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
      - "bug fix"
  - title: "Infrastructure"
    labels:
      - "infra"
      - "test"
      - "dependencies"
      - "github actions"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Maintenance"
    labels:
      - "version upgrade"
      - "odfe release"
  - title: "Refactoring"
    labels:
      - "refactor"
      - "code quality"
